apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python
  name: python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - image: rtprosa315/jenkins:xxx
        name: python
        ports:
        - containerPort: 80
