apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python
  name: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - image: rtprosa315/jenkins:xxx
        name: python
        ports:
        - containerPort: 80
      containers:
      - image: nginx
        name: python
        ports:
        - containerPort: 8080
      volumes:
      - name: configmap
        configMap:
          name: nginx-config

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: python
  name: python
  namespace: python-test
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  type: NodePort

---
apiVersion: v1
data:
  nginx.config: |-
    server {
        listen 80;

        location / {
            include uwsgi_params;
            uwsgi_pass flask:8080;
        }
    }
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: python-test
